from src.automata import *
from src.automata_util import *

if __name__ == '__main__':
    nd = NDAutomata()
    nd.add_word("auto", lambda: print("lul"))
    nd.add_word("automovil", lambda: print("lula"))
    nd.add_word("autobus", lambda: print("lulaaaa"))
    nd.add_word("casa", lambda: print("casa"))
    da = determinize_automata(nd)
    print("nd: ")
    nd.consume_stream("<html>")
    nd.consume_stream("<head>")
    nd.consume_stream("<title>Archivo de ejemplo</title>")
    nd.consume_stream("</head>")
    nd.consume_stream("<body>")
    nd.consume_stream("<h1 align=\"center\">Este es otro archivo de ejemplo</h1>")
    nd.consume_stream("<h2>Test</h2>")
    nd.consume_stream("<p>auto auto auto, automovil, autobus, casa, casado</p>")
    nd.consume_stream("</body>")
    print("\nda: ")
    nd.consume_stream("<html>")
    nd.consume_stream("<head>")
    nd.consume_stream("<title>Archivo de ejemplo</title>")
    nd.consume_stream("</head>")
    nd.consume_stream("<body>")
    nd.consume_stream("<h1 align=\"center\">Este es otro archivo de ejemplo</h1>")
    nd.consume_stream("<h2>Test</h2>")
    nd.consume_stream("<p>auto casa auto auto, automovil, autobus, casa, casado</p>")
    nd.consume_stream("</body>")
